# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YzIyOTZiYzE3ODM5NmU2MTAyMDRkYmY1MzczMDI5NmI3ZDBkMGJhZWM1NTQxNTQwMDEyM2QxMDBlYTAxMjA5MmE2Y2E5NjY5YWMwMDI5ODRkMDFiMjE3ZDk5YzhmY2E3ZDUyZGZmYzQ4NjI1YmE2NWNlNGJlZDU0OWRlMzZkOTc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
